### ISSUE TITLE
undefined method `item' for #<Arena::Channel:0x00007f2f25155198>

### ISSUE THREAD

**Issue by dblock** [dblock/slack-arena#11]
```
W, [2018-05-22T12:24:59.338660 #221]  WARN -- : Error in cron for team name=playplay, id=T0H0YREAD, undefined method `item' for #<Arena::Channel:0x00007f2f25155198>, /app/slack-arena/models/arena/followed.rb:57:in `block_color'
/app/slack-arena/models/arena/followed.rb:82:in `block'
/app/slack-arena/models/channel.rb:82:in `block in sync!'
/app/slack-arena/models/channel.rb:77:in `each'
/app/slack-arena/models/channel.rb:77:in `sync!'
/app/slack-arena/models/channel.rb:29:in `sync_new_arena_items!'
/app/vendor/bundle/ruby/2.5.0/gems/mongoid-7.0.0/lib/mongoid/association/referenced/has_many/proxy.rb:162:in `block in each'
/app/vendor/bundle/ruby/2.5.0/gems/mongoid-7.0.0/lib/mongoid/association/referenced/has_many/enumerable.rb:190:in `block in each'
/app/vendor/bundle/ruby/2.5.0/gems/mongoid-7.0.0/lib/mongoid/contextual/mongo.rb:705:in `yield_document'
/app/vendor/bundle/ruby/2.5.0/gems/mongoid-7.0.0/lib/mongoid/contextual/mongo.rb:134:in `block in each'
/app/vendor/bundle/ruby/2.5.0/gems/mongo-2.5.1/lib/mongo/collection/view/iterable.rb:46:in `block in each'
/app/vendor/bundle/ruby/2.5.0/gems/mongo-2.5.1/lib/mongo/cursor.rb:121:in `block in each'
/app/vendor/bundle/ruby/2.5.0/gems/mongo-2.5.1/lib/mongo/cursor.rb:121:in `each'
/app/vendor/bundle/ruby/2.5.0/gems/mongo-2.5.1/lib/mongo/cursor.rb:121:in `each'
/app/vendor/bundle/ruby/2.5.0/gems/mongo-2.5.1/lib/mongo/collection/view/iterable.rb:45:in `each'
/app/vendor/bundle/ruby/2.5.0/gems/mongoid-7.0.0/lib/mongoid/query_cache.rb:222:in `each'
/app/vendor/bundle/ruby/2.5.0/gems/mongoid-7.0.0/lib/mongoid/contextual/mongo.rb:133:in `each'
/app/vendor/bundle/ruby/2.5.0/gems/mongoid-7.0.0/lib/mongoid/contextual.rb:20:in `each'
/app/vendor/bundle/ruby/2.5.0/gems/mongoid-7.0.0/lib/mongoid/association/referenced/has_many/enumerable.rb:186:in `each'
/app/vendor/bundle/ruby/2.5.0/gems/mongoid-7.0.0/lib/mongoid/association/referenced/has_many/proxy.rb:162:in `each'
/app/slack-arena/app.rb:52:in `block in sync!'
```

**Comment by dblock** [comment]
Closed via https://github.com/dblock/slack-arena/commit/4bf043209cbb40191cc0f7a52a61141f802c7eae
